dist: focal
language: python
python:
  - "3.10"
install:
  - pip install -r requirements.txt
  - pip install -r docs/requirements.txt
  - pip install pytest-cov
script:
  - pytest --cov=sphinx_readme tests/
after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov
