name: "Deploy Sphinx gh-pages"
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build doc
      run: |
        sudo apt-get --allow-releaseinfo-change update -y 
        sudo apt-get install -y git make sphinx
        pip install -r requirements.txt
        pip install -r docs/requirements.txt
        make -C docs html

    - name: Commit documentation changes
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        force_orphan: true